# TZ = "UK"

[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
 HUGO_VERSION = "0.139.4"
 HUGO_ENV = "production"
 HUGO_ENABLEGITINFO = "false"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

	[plugins.inputs]
	# If it should show more verbose logs (optional, default = true)
	debug = true
	# Relative path to source directory in case you use Hugo's "--s" option
	srcdir = "path/to/website"